version: 2.1

workflows:
  build-deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - setup_remote_docker:
          version: 20.10.18
      - checkout
      - run: 
            name: "Setup custom environment variables"
            command: |
                        echo 'export MY_VERSION="1.1"' >> $BASH_ENV
                        echo "export MY_HASH=$(git --no-pager log --pretty=format:\"%h\" -1)" >> $BASH_ENV
                        echo 'export DOCKERHUB_USER=${DOCKERHUB_USER}' >> $BASH_ENV
                        echo 'export DOCKERHUB_PASSWORD=${DOCKERHUB_PASSWORD}' >> $BASH_ENV
      - run: 
            name: "Setting up Buildx Environment" 
            command: |
                        docker context create buildx-build
                        docker buildx create --use buildx-build
                        docker run --privileged --rm tonistiigi/binfmt --install all
      - run: 
            name: "Logging in to DockerHub" 
            command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin                     
      - run: 
            name: "Creating Container"
            command: docker buildx build --push --platform linux/arm64,linux/amd64 --tag rustic/docker-timemachine:latest --tag rustic/docker-timemachine:${MY_VERSION} --build-arg VCS_REF=${MY_HASH} --build-arg VERSION=${MY_VERSION} .
